[package]
name = "text-edit"
version = "0.1.0"
edition = "2021"

[dependencies]
similar = "2.6"
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "serde_json"]
